# Generated by Django 3.1.3 on 2020-12-01 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('employee_surname', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('employee_age', models.PositiveIntegerField(default=1, null=True, verbose_name='Вік')),
                ('employee_address', models.CharField(max_length=1024, null=True, verbose_name='Адреса')),
                ('employee_telephone', models.CharField(max_length=13, null=True, verbose_name='Номер телефону')),
                ('employee_passport_data', models.CharField(max_length=9, verbose_name='Паспортні дані')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50, verbose_name='Назва жанру')),
                ('genre_description', models.TextField(default='Опис жанру відсутній.', null=True, verbose_name='Опис жанру')),
                ('genre_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=80, verbose_name='Назва фільму')),
                ('movie_duration', models.PositiveIntegerField(default=1, null=True, verbose_name='Тривалість фільму(у хвилинах)')),
                ('movie_producer', models.TextField(verbose_name='Продюсер')),
                ('movie_country', models.CharField(max_length=80, null=True, verbose_name='Країна фільму')),
                ('movie_age_restrictions', models.PositiveIntegerField(default=1, null=True, verbose_name='Вікові обмеження')),
                ('movie_actors', models.TextField(null=True, verbose_name='Актори')),
                ('movie_description', models.TextField(default='Опис фільму відсутній.', null=True, verbose_name='Опис')),
                ('movie_thumbnail', models.ImageField(upload_to='', verbose_name='Постер фільму')),
                ('movie_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occ_name', models.CharField(max_length=50, verbose_name='Назва посади')),
                ('occ_salary', models.PositiveIntegerField(default=1, null=True, verbose_name='Зарплата')),
                ('occ_responsibilities', models.CharField(max_length=255, null=True, verbose_name="Обов'язки")),
                ('occ_requirements', models.CharField(max_length=255, null=True, verbose_name='Вимоги')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(default=1, verbose_name='Номер місця')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(verbose_name='Дата')),
                ('session_price', models.PositiveIntegerField(default=1, verbose_name='Ціна квитка')),
                ('session_slug', models.SlugField(unique=True)),
                ('session_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApplication.movieunit', verbose_name='Код Фільму')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_Occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApplication.occupation', verbose_name='Код посади')),
                ('worker_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApplication.employees', verbose_name='Код працівника')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApplication.seats', verbose_name='Код Місця')),
                ('ticket_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApplication.session', verbose_name='Код Сеансу')),
                ('ticket_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApplication.workers', verbose_name='Код працівника')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApplication.genres', verbose_name='Код Жанру')),
                ('movie_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApplication.movieunit', verbose_name='Код Фільму')),
            ],
        ),
    ]
